### ISSUE TITLE
missing type for domNode.children

### ISSUE THREAD

**Issue by alex4brandung** [remarkablemark/html-react-parser#1211]
I set up the following options:

```ts
const options: HTMLReactParserOptions = {
    replace(domNode: DOMNode) {
      if ((domNode as Element).attribs && (domNode as Element).name === 'a') {
        const props = attributesToProps((domNode as Element).attribs);
        return (
          <a className={'text-heaven'} {...props}>
            {domToReact((domNode as Element).children, options)}
          </a>
        );
      }
    },
  };
```

I am getting the following Error in my IDE:

![Bildschirmfoto 2023-12-06 um 17 18 31](https://github.com/remarkablemark/html-react-parser/assets/137274125/82b09b1c-b845-41a7-980c-1a41e36b862d)

**Comment by remarkablemark** [comment]
@alex4brandung can you try this? https://github.com/remarkablemark/html-react-parser/tree/v5.0.7#v5

**Comment by alex4brandung** [comment]
I import it as es6 module...

**Comment by alex4brandung** [comment]
```ts
{domToReact((domNode as Element).children as DOMNode[], options)}
```
fixed it! Thanks for the hint!

**Comment by cini9** [comment]
Hey @alex4brandung thanks for the awesome lib. I'm still getting some typescript errors using domToReact in NextJS 13. My html-react-parser version is 5.1.7 and this is my code :

![Screenshot 2024-02-21 at 13 53 33](https://github.com/remarkablemark/html-react-parser/assets/56114997/ddd5598f-c9e2-4f73-bb88-e957c48eb7cc)
